name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Trigger redeploy for Docker host, via Home Assistant webhook
      run: curl -X POST "https://ha57012339e.andrewholloway.info/api/webhook/${{ secrets.HA_WEBHOOK_KEY }}"
